# Generated by Django 5.0.2 on 2024-02-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Id', models.CharField(blank=True, max_length=10)),
                ('product_Name', models.CharField(blank=True, max_length=10)),
                ('vendor', models.CharField(blank=True, max_length=10)),
                ('mrp', models.CharField(blank=True, max_length=10)),
                ('batch_num', models.CharField(blank=True, max_length=10)),
                ('batch_date', models.CharField(blank=True, max_length=10)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('approved', 'Approved'), ('pending', 'Pending'), ('other', 'Other')], max_length=10)),
            ],
            options={
                'db_table': 'records',
            },
        ),
    ]
