# Generated by Django 5.0.2 on 2024-02-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecords',
            name='batch_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='inventoryrecords',
            name='mrp',
            field=models.FloatField(),
        ),
    ]
