# Generated by Django 5.0.2 on 2024-02-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_inventoryrecords_batch_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecords',
            name='product_Id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
