# Generated by Django 5.0.2 on 2024-02-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_inventoryrecords_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecords',
            name='batch_date',
            field=models.DateField(),
        ),
    ]
