# Generated by Django 5.0.2 on 2024-02-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_inventoryrecords_batch_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.CharField(max_length=255)),
                ('request_status', models.CharField(blank=True, choices=[('approved', 'Approved'), ('pending', 'Pending'), ('reject', 'Reject')], max_length=10)),
                ('action', models.CharField(blank=True, choices=[('edit', 'Edit'), ('delete', 'Delete'), ('add', 'Add')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='inventoryrecords',
            name='status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('pending', 'Pending')], max_length=10),
        ),
    ]
