# Generated by Django 5.0.2 on 2024-02-15 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_inventory_product_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.CharField(max_length=255)),
                ('request_status', models.CharField(blank=True, choices=[('approved', 'Approved'), ('pending', 'Pending'), ('reject', 'Reject')], max_length=10)),
                ('action', models.CharField(blank=True, choices=[('edit', 'Edit'), ('delete', 'Delete'), ('add', 'Add')], max_length=10)),
                ('requested_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='InventoryApproval',
        ),
    ]
